name: github-action-pipeline
on: #["push","pull_request","workflow_dispatch"]
  workflow_dispatch:
  # push:
  #   branches: 
  #     - main
  #     - dev
  #     - prod
  #     - feature/*
  # #push:
  #  # branches: [ "main" ]
  # #pull_request:
  #   #branches: [ "main" ]
  # pull_request:
  #   types:
  #     - opened
  #     - synchronize
  #     - reopened
  #   branches:
  #     - main
  #     - feature/*
  

  #workflow_dispatch:
jobs:
  build-job-name:
    runs-on: ubuntu-latest
    steps:
     #- uses: actions/checkout@v4
      - name: Run a one-line script
        run: |
          echo Hello, world ${{vars.MY_NAME}}! This is my first github action pipeline.
          ${{secrets.MY_DOCKER_PASSWORD}}
        # run: echo "this is build job!"

  # test-job-name:
  #   runs-on: macos-latest
  #   needs: build-job-name
  #   steps:
  #     - name: Run a one-line script
  #       run: echo Hello, world!
  #     - name: Run a multi-line script
  #       run: echo this is test job!

  # deploy-job-name:
  #   runs-on: windows-latest
  #   needs: test-job-name
  #   steps:
  #     - name: Run a one-line script
  #       run: echo this is deploy job!
  #     - name: Run a multi-line script
  #       run: |
  #         echo Add other actions to build,
  #         echo test, and deploy your project.
  #         echo "Happy coding!"